import fs from 'fs-extra';
import { join } from 'path';
import { getRunDir } from '../core/state/index.js';
import { emitArtifactSaved } from './events.js';

export type ArtifactCategory =
  | 'screenshots'
  | 'traces'
  | 'logs'
  | 'diffs'
  | 'reports';

export async function saveArtifact(
  runId: string,
  category: ArtifactCategory,
  filename: string,
  content: string | Buffer,
  baseDir?: string,
): Promise<string> {
  const dir = getRunDir(runId, baseDir);
  const artifactPath = join(dir, 'artifacts', category, filename);
  await fs.ensureDir(join(dir, 'artifacts', category));
  if (typeof content === 'string') {
    await fs.writeFile(artifactPath, content, 'utf-8');
  } else {
    await fs.writeFile(artifactPath, content);
  }
  emitArtifactSaved(runId, artifactPath);
  return artifactPath;
}

export async function saveScreenshot(
  runId: string,
  viewport: string,
  route: string,
  imageBuffer: Buffer,
  baseDir?: string,
): Promise<string> {
  const sanitizedRoute = route.replace(/\//g, '_').replace(/^_/, '') || 'root';
  const filename = `${sanitizedRoute}-${viewport}.png`;
  return saveArtifact(runId, 'screenshots', filename, imageBuffer, baseDir);
}

export async function saveDiff(
  runId: string,
  filename: string,
  content: string,
  baseDir?: string,
): Promise<string> {
  return saveArtifact(runId, 'diffs', filename, content, baseDir);
}

export async function saveReport(
  runId: string,
  filename: string,
  content: string,
  baseDir?: string,
): Promise<string> {
  return saveArtifact(runId, 'reports', filename, content, baseDir);
}

export async function saveLog(
  runId: string,
  filename: string,
  content: string,
  baseDir?: string,
): Promise<string> {
  return saveArtifact(runId, 'logs', filename, content, baseDir);
}

export async function saveFinalSummary(
  runId: string,
  summary: string,
  scorecard: Record<string, unknown>,
  outcome: Record<string, unknown>,
  baseDir?: string,
): Promise<void> {
  const dir = getRunDir(runId, baseDir);
  await fs.ensureDir(join(dir, 'final'));
  await fs.writeFile(join(dir, 'final', 'summary.md'), summary);
  await fs.writeJson(join(dir, 'final', 'scorecard.json'), scorecard, {
    spaces: 2,
  });
  await fs.writeJson(join(dir, 'final', 'outcome.json'), outcome, {
    spaces: 2,
  });
}

export async function listArtifacts(
  runId: string,
  category?: ArtifactCategory,
  baseDir?: string,
): Promise<string[]> {
  const dir = getRunDir(runId, baseDir);
  const root = join(dir, 'artifacts');
  if (category) {
    const catDir = join(root, category);
    if (!(await fs.pathExists(catDir))) return [];
    const files = await fs.readdir(catDir);
    return files.map((f) => join(catDir, f));
  }
  const categories: ArtifactCategory[] = [
    'screenshots',
    'traces',
    'logs',
    'diffs',
    'reports',
  ];
  const all: string[] = [];
  for (const cat of categories) {
    const catDir = join(root, cat);
    if (await fs.pathExists(catDir)) {
      const files = await fs.readdir(catDir);
      all.push(...files.map((f) => join(catDir, f)));
    }
  }
  return all;
}

export async function writeEscalationPacket(
  runId: string,
  packet: {
    summary: string;
    failingIssues: string;
    attemptsCount: number;
    triedSolutions: string[];
    likelyRootCause: string;
    recommendedDecision: string;
  },
  baseDir?: string,
): Promise<string> {
  const dir = getRunDir(runId, baseDir);
  await fs.ensureDir(join(dir, 'review'));
  const content = [
    `# Human Review Required`,
    ``,
    `## Run Summary`,
    packet.summary,
    ``,
    `## Failing Issues`,
    packet.failingIssues,
    ``,
    `## Attempts`,
    `${packet.attemptsCount} automated repair attempts made.`,
    ``,
    `## What Was Tried`,
    ...packet.triedSolutions.map((s) => `- ${s}`),
    ``,
    `## Likely Root Cause`,
    packet.likelyRootCause,
    ``,
    `## Recommended Decision`,
    packet.recommendedDecision,
    ``,
    `---`,
    `_Generated by mAIker at ${new Date().toISOString()}_`,
  ].join('\n');

  const path = join(dir, 'review', 'human-review.md');
  await fs.writeFile(path, content);
  return path;
}
